name: Burpsuite 
on: 

  workflow_dispatch:

jobs:
  DAST_SCAN:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dast scan
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: https://jonbarron.info/

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.xml
           

    
          
           
       
  
