name: Burpsuite 
on: 

  workflow_dispatch:

jobs:
  Dastscan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dast scan
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: https://gem.gov.in/
          output-filename: dastardly-report.xml

      - name: check if report exist
        run: ls -la

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dastardly-report.xml
          path: dastardly-report.xml
           

    
          
           
       
  
